// src/modules/groq_ai_insights/emailService.js
// ─────────────────────────────────────────────────────────────────────────────
// EMAIL SERVICE — NodeMailer SMTP Dispatcher
// ─────────────────────────────────────────────────────────────────────────────
// Wraps NodeMailer to send AI-generated emails.
// Supports both HTML (styled) and plain text fallback.
// ─────────────────────────────────────────────────────────────────────────────
'use strict';

require('dotenv').config();
const nodemailer = require('nodemailer');

// ── Create reusable SMTP transport ────────────────────────────────────────────
const transporter = nodemailer.createTransport({
  host:   process.env.SMTP_HOST || 'smtp.gmail.com',
  port:   parseInt(process.env.SMTP_PORT) || 587,
  secure: false,    // true for port 465, false for 587 (STARTTLS)
  auth: {
    user: process.env.SMTP_USER,
    pass: process.env.SMTP_PASS,
  },
});

/**
 * Converts plain text email body into a styled HTML email.
 * Uses inline CSS for maximum email client compatibility.
 *
 * @param {string} subject     - Email subject line
 * @param {string} body        - Plain text content from Groq AI
 * @param {string} studentName - Used in the email header banner
 */
function buildHtmlEmail(subject, body, studentName) {
  // Convert plain text paragraphs → HTML paragraphs
  const htmlBody = body
    .split('\n')
    .filter(line => line.trim())
    .map(line => `<p style="margin:0 0 12px 0; line-height:1.6;">${line}</p>`)
    .join('\n');

  return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${subject}</title>
</head>
<body style="margin:0; padding:0; background-color:#f4f7fb; font-family: 'Segoe UI', Arial, sans-serif;">

  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f4f7fb; padding:30px 0;">
    <tr>
      <td align="center">
        <table width="600" cellpadding="0" cellspacing="0" style="max-width:600px; width:100%; background:#ffffff; border-radius:12px; overflow:hidden; box-shadow:0 4px 20px rgba(0,0,0,0.08);">

          <!-- Header Banner -->
          <tr>
            <td style="background: linear-gradient(135deg, #6366f1, #8b5cf6); padding:32px 40px; text-align:center;">
              <h1 style="margin:0; color:#ffffff; font-size:24px; font-weight:700; letter-spacing:-0.5px;">
                📚 Hasi Tuition Classes
              </h1>
              <p style="margin:8px 0 0; color:rgba(255,255,255,0.85); font-size:14px;">
                Student Progress Update
              </p>
            </td>
          </tr>

          <!-- Student Name Badge -->
          <tr>
            <td style="background:#f0edff; padding:16px 40px; border-bottom:1px solid #e5e7eb;">
              <p style="margin:0; color:#6366f1; font-size:14px; font-weight:600; text-transform:uppercase; letter-spacing:0.5px;">
                📋 Report for
              </p>
              <h2 style="margin:4px 0 0; color:#1f2937; font-size:20px; font-weight:700;">
                ${studentName}
              </h2>
            </td>
          </tr>

          <!-- AI-Generated Email Body -->
          <tr>
            <td style="padding:32px 40px; color:#374151; font-size:15px;">
              ${htmlBody}
            </td>
          </tr>

          <!-- Divider -->
          <tr>
            <td style="padding:0 40px;">
              <hr style="border:none; border-top:1px solid #e5e7eb; margin:0;">
            </td>
          </tr>

          <!-- AI Badge -->
          <tr>
            <td style="padding:16px 40px; background:#fafafa;">
              <p style="margin:0; color:#9ca3af; font-size:12px; text-align:center;">
                ✨ This report was generated by <strong>Groq AI (llama-3.3-70b-versatile)</strong>
                and sent automatically by the Hasi Tuition Management System.
              </p>
            </td>
          </tr>

          <!-- Footer -->
          <tr>
            <td style="background:#6366f1; padding:20px 40px; text-align:center;">
              <p style="margin:0; color:rgba(255,255,255,0.8); font-size:13px;">
                © 2026 Hasi Tuition Classes · Powered by AI
              </p>
            </td>
          </tr>

        </table>
      </td>
    </tr>
  </table>
</body>
</html>
  `.trim();
}

/**
 * Sends an AI-generated progress email to the student/guardian.
 *
 * @param {Object} options
 * @param {string} options.to          - Recipient email address
 * @param {string} options.subject     - Email subject
 * @param {string} options.body        - Plain-text body (from Groq)
 * @param {string} options.studentName - For the HTML template header
 *
 * @returns {Promise<Object>} NodeMailer send result
 */
async function sendProgressEmail({ to, subject, body, studentName }) {
  if (!process.env.SMTP_USER || !process.env.SMTP_PASS) {
    console.warn('[Email] ⚠️  SMTP credentials not configured. Email skipped (logged to DB only).');
    return { skipped: true, reason: 'SMTP_NOT_CONFIGURED' };
  }

  const mailOptions = {
    from:    process.env.EMAIL_FROM || `"Hasi Tuition" <${process.env.SMTP_USER}>`,
    to,
    subject,
    text:    body,                                      // Plain text fallback
    html:    buildHtmlEmail(subject, body, studentName), // Styled HTML version
  };

  const result = await transporter.sendMail(mailOptions);

  console.log(`[Email] ✅ Sent to ${to} | MessageId: ${result.messageId}`);

  return result;
}

/**
 * Verifies SMTP connection — call at module startup to catch misconfig early.
 */
async function verifySmtpConnection() {
  if (!process.env.SMTP_USER || !process.env.SMTP_PASS) {
    console.warn('[Email] ⚠️  SMTP not configured — emails will be skipped but logged.');
    return false;
  }

  try {
    await transporter.verify();
    console.log('[Email] ✅ SMTP connection verified successfully.');
    return true;
  } catch (err) {
    console.warn('[Email] ⚠️  SMTP verification failed:', err.message);
    return false;
  }
}

module.exports = { sendProgressEmail, verifySmtpConnection };
